name: docker

on:
  push:
    branches:
      - 'main'
    tags:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: rsteube/carapace

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }}
