name: Go

on:
  pull_request:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    container: ghcr.io/rsteube/carapace
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Build
      run: cd example && go build -v .

    - name: "Check formatting"
      run: '[ "$(gofmt -d -s . | tee -a /dev/stderr)" = "" ]'

    - name: "staticcheck"
      run: go install honnef.co/go/tools/cmd/staticcheck@2021.1.1 && staticcheck ./...

    - name: "shellcheck bash"
      run: |
        ./example/example _carapace bash > /tmp/bash.sh
        shellcheck -e SC2046,SC2206,SC2207 /tmp/bash.sh

    - name: "shellcheck fish"
      run: |
        ./example/example _carapace fish > /tmp/fish.sh
        shellcheck -e SC1064,SC1072,SC1073 /tmp/fish.sh

    - name: "PSScriptAnayzer powershell"
      run: |
        ./example/example _carapace powershell > /tmp/powershell.ps1
        pwsh -Command "Invoke-ScriptAnalyzer -Path /tmp/powershell.ps1" -EnableExit

    - name: "shellcheck zsh"
      run: |
        ./example/example _carapace zsh > /tmp/zsh.sh
        shellcheck -e SC2148,SC2154 /tmp/zsh.sh

    - name: Test
      run: PATH=$(pwd):$PATH go test -coverprofile=coverage.out -v ./...

    - uses: codecov/codecov-action@v2

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  doc:
    runs-on: ubuntu-latest
    container: ghcr.io/rsteube/carapace
    steps:
      - uses: actions/checkout@v2
      - name: "build docs"
        run: |
            sed -i 's/\[output.linkcheck\]/#[output.linkcheck]/' docs/book.toml
            mdbook build docs
      - name: "push gh-pages"
        if: github.ref == 'refs/heads/master'
        run: |
            cd docs/book/
            git init
            git config user.name rsteube
            git config user.email rsteube@users.noreply.github.com
            git add .
            git commit -m "initial commit [ci skip]"
            git push --force https://rsteube:${GITHUB_TOKEN}@github.com/rsteube/carapace.git master:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
